function stringbasic() {
    console.log("My dream company: Google");
}

stringbasic();

function logHobbies() {
    
    var hobby1 = "Reading";
    var hobby2 = "Coding";
    var hobby3 = "Traveling";

    console.log("My hobbies are:", hobby1 + ",", hobby2 + ",", hobby3);

    var totalCharacters = hobby1.length + hobby2.length + hobby3.length;
    console.log("Total number of characters in hobbies:", totalCharacters);
}

logHobbies();

